# config/routes.yaml
add:
    path: /add
    controller: App\Controller\UserController::index

login:
    path: /login
    controller: App\Controller\AuthController::login


vehicule:
    path: /vehicule/new
    controller: App\Controller\VehiculeController::new

vehicule_edit:
    path: /vehicule/{id}/edit
    controller: App\Controller\VehiculeController::edit

vehicule_show:
    path: /
    controller: App\Controller\VehiculeController::show
legal:
    path: /mentions-legales
    controller: App\Controller\LegalController::index


    
