doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: 'localhost'
        port: 3306
        dbname: 'blog'
        user: 'demo'
        password: 'demo'
        charset: UTF8
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

    # Vous pouvez ajouter d'autres configurations ici, comme "when@test" ou "when@prod".
